### ISSUE TITLE
Breaking Speaker In Creative Causes Client Crash on Dedicated Server - 1.12.2

### ISSUE THREAD

**Issue by Baitslunk** [NicholasFeldman/BetterRecords#26] opened 2018-01-20 21:45 UTC
<a href="https://github.com/P3rf3ctXZer0"><img src="https://avatars3.githubusercontent.com/u/10351221?v=4" align="left" width="96" height="96" hspace="10"></img></a> **Issue by [P3rf3ctXZer0](https://github.com/P3rf3ctXZer0)**
_Mon Jan 15 19:47:34 2018_
_Originally opened as https://github.com/Stumblinbear/BetterRecords/issues/54_

----

Code Right After Crash 
https://gist.github.com/P3rf3ctXZer0/65d17669bb7728cec8dcd853747f147f

Crash Log
https://gist.github.com/P3rf3ctXZer0/4227a668b447392d5a82af4c23e2482f

Client Log
https://gist.github.com/P3rf3ctXZer0/44b9ce7db580042534908c4e9ee14850

Latest
https://gist.github.com/P3rf3ctXZer0/a4fb96b408e7e1628e9325617d017ac5

Server  Latest 
https://gist.github.com/P3rf3ctXZer0/6d6a058059ce7b5d6cef9d4fb7901652

**Comment by Baitslunk** [comment] 2018-01-20 21:45
<a href="https://github.com/NicholasFeldman"><img src="https://avatars3.githubusercontent.com/u/1383438?v=4" align="left" width="48" height="48" hspace="10"></img></a> **Comment by [NicholasFeldman](https://github.com/NicholasFeldman)**
_Mon Jan 15 22:26:08 2018_

----

I'm unable to reproduce this. Please provide the information available in the Issue template:
```
BetterRecords: `version`  
Forge: `version`

# Issue
Describe the problem here

# Steps to Reproduce
1.
2.
3. 

Link to crash log: <Preferably Gist or Pastebin> 
```

Also, it looks like you're using FoamFix, try removing it and let me know if the issue still occurs.

**Comment by Baitslunk** [comment] 2018-01-20 21:45
<a href="https://github.com/P3rf3ctXZer0"><img src="https://avatars3.githubusercontent.com/u/10351221?v=4" align="left" width="48" height="48" hspace="10"></img></a> **Comment by [P3rf3ctXZer0](https://github.com/P3rf3ctXZer0)**
_Mon Jan 15 22:40:38 2018_

----

Okay. I will make a video when I get a chance. For the time being I just disabled the recipe XD

**Comment by Baitslunk** [comment] 2018-01-20 21:45
<a href="https://github.com/P3rf3ctXZer0"><img src="https://avatars3.githubusercontent.com/u/10351221?v=4" align="left" width="48" height="48" hspace="10"></img></a> **Comment by [P3rf3ctXZer0](https://github.com/P3rf3ctXZer0)**
_Mon Jan 15 22:42:11 2018_

----

OH I should specify it only occurs on a dedicated server not single player.

**Comment by NicholasFeldman** [comment] 2018-01-21 02:36
Closed, unable to reproduce and no response

**Comment by JoeJoeTV** [comment] 2018-01-21 12:23
I have this issue too and to reproduce it you need to set up a forge dedicated server with Forge 1.12.2-14.23.1.2582. Then you need to set up a record player with a large speaker attatched, play music and break the speaker in creative mode. It might need a few tries and you need to try on the upper and lower half.

Better Records 1.5.1
Forgelin 1.6.0

**Comment by NicholasFeldman** [comment] 2018-01-21 12:27
Thanks, I'll look into it

**Comment by P3rf3ctXZer0** [comment] 2018-01-21 16:38
I did the upper half

**Comment by P3rf3ctXZer0** [comment] 2018-01-21 16:40
@NicholasFeldman sorry I have been too busy to test thoroughly I am sorry in the future if I feel an issue is fixed I can close my own issues. When I am too busy I just remove the offending mod and continue on with life.

**Comment by NicholasFeldman** [comment] 2018-01-21 22:32
If you feel like an issue is fixed yes, you are free to close it. However I am too after prompting twice for basic information you failed to provide.

**Comment by NicholasFeldman** [comment] 2018-01-21 22:39
I tried for about ten minutes to reproduce this with the steps provided by @JoeJoeTV, and was still unable to reproduce this on BetterRecords 1.5.4.

Do you both have `foamfix-anarchy` present?

**Comment by P3rf3ctXZer0** [comment] 2018-01-22 00:21
no
only client side.

**Comment by NicholasFeldman** [comment] 2018-01-22 00:26
So, it is. Have you been able to reproduce this with `foamfix-lawful`, or no foamfix at all? Anarchy contains a coremod which makes a lot of changes, and may cause incompatibilities with other mods. Hence why lawful exists.

Most mods will not accept a crash report if foamfix anarchy is present at all.

**Comment by P3rf3ctXZer0** [comment] 2018-01-22 16:41
Lawful does not exist for 1.12.2 as @ascribed just sort of poofed.

**Comment by JoeJoeTV** [comment] 2018-01-22 18:20
Lawful does exist for 1.12.2. Here: https://asie.pl/files/mods/FoamFix/ 
And i did have it in the modpack so could that have been the issue and is there a way to fix it?

**Comment by P3rf3ctXZer0** [comment] 2018-01-22 20:47
At any rate even with all core mods (Including foamfix)gone I can still create the crash. At any rate its not too important to me I just disabled speaker recipe though since everything else works you could also add a way to disable speakers in config since I have had people abuse them in the past not to mention it only crashes client and the speaker does break.

Also lastly I can break the game without being in creative. I have only tested on large speakers.

**Comment by NicholasFeldman** [comment] 2018-01-22 20:52
Abuse how?

I'm still interested in resolving this, I'll try later to recreate it again when one of my testers are available, but it's weird because I'm still unable to. 

Are you trying with version 1.5.4?

**Comment by P3rf3ctXZer0** [comment] 2018-01-22 21:05
Thut says you need to fix this
![2018-01-22 15_01_10- thutmose - discord](https://user-images.githubusercontent.com/10351221/35244421-e77ec760-ff74-11e7-8305-9d8692e9e323.png)

**Closed** 2018-01-23 04:08 UTC
Labels: Bug

**Comment by NicholasFeldman** [comment] 2018-01-23 17:24
I did some more testing with this, turns out it only happens when the client/server pc are too slow, and tick while the block is being removed.

I was finally able to reproduce this by running in a virtual machine limited to 1GB ram and cpu clock cycles limited to 2Ghz.

[The fix has been included in our latest release](https://minecraft.curseforge.com/projects/better-records/files)
