### ISSUE TITLE
My music doesn't sound

### ISSUE THREAD

**Issue by marioateru** [NicholasFeldman/BetterRecords#71] opened 2018-11-17 17:01 UTC
BetterRecords: 17/11/2018
Forge: 

# Issue
When I download and play my music, it doesn't sound. I connected stereos but nothing happenned

# Steps to Reproduce
1.Download music from dropbox
2.Put the record on the machine

**Comment by P3rf3ctXZer0** [comment] 2018-11-17 17:03
This a dupe of this issue.

**Closed** 2018-11-17 18:10 UTC
Labels: Bug, Duplicate
