### ISSUE TITLE
Volume Sliders greatly influence range.

### ISSUE THREAD

**Issue by Rsslone** [NicholasFeldman/BetterRecords#99] opened 2020-03-07 20:51 UTC
BetterRecords: `BetterRecords-1.12.2-1.6.1`  
Forge: `forge-1.12.2-14.23.5.2847-universal`

# Issue
The range seems to be tied to the volume sliders and instead of the source audio volume decreasing it decreases the range at which the audio is heard, this includes the master audio slider. If I set the audio sliders down to a reasonable volume, even though I'm at 200 block range, the sound vanishes within 30ish blocks.

**Comment by NicholasFeldman** [comment] 2020-05-19 22:25
Duplicate of #104 (yes I know this one was first, but I'm keeping that issue on my board because it's more descriptive

**Closed by NicholasFeldman** 2020-05-19 22:25 UTC
